server:
  port: 20000

spring:
  application:
    name: damimall-auth

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  thymeleaf:
    cache: false

  redis:
    host: 192.168.83.129
    port: 6379
    password: 123456

  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1
