server:
  port: 15000

spring:
  application:
    name: damimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1

  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
