server:
  port: 14001

spring:
  application:
    name: damimall-member
  datasource:
    class-driver-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/damimall_ums?serverTimeZone=UTC
    username: root
    password: 159357qazQAZ
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  thymeleaf:
    cache: false

  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
